server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
spring:
  application:
    name: zero_to_hero_rules_engine
  datasource:
    username: dear
    password: comrade
    #url: jdbc:postgresql://172.19.0.2:5432/dear_comrade
    url: jdbc:postgresql://localhost:5432/dear_comrade
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
        show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
drool:
  template: rools/route.drl
  drool-domine-name: ruleResult
  title: Comrade Drool Engine
  nav-name: Comrade Rules
  header-title: Telangana Travel Rules
  add-condition: Conditions